algoritmo "semnome"
// 13) Informado 3 números, apresente a soma do primeiro com o terceiro, multiplicando pelo segundo.
var
 N1,N2,N3,Resultado:real
inicio
escreva("Digite o valor do primeiro Numero:")
leia (N1)
escreva("Digite o valor do segundo Numero:")
leia (N2)
escreva("Digite o valor do terceiro Numero:")
leia (N3)
Resultado <- ((N1 + N3) * N2)
escreval ("O valor da Resultado é: ",Resultado)
fimalgoritmo
