algoritmo "semnome"
// 14) Sendo dado dois números pelo usuário, apresente a décima parte da subtração de um pelo outro, utilizando uma terceira variável
var
 V1,V2,DPart:real
inicio
escreva("Digite o valor do primeiro Numero:")
leia (V1)
escreva("Digite o valor do segundo Numero:")
leia (V2)
DPart <- ((V1 - V2) /10)
escreval ("A decima Parte da Subtração dos dois numeros é: ",DPart)
fimalgoritmo
