algoritmo "semnome"
//25) Construa um algoritmo que solicite três valores e apresente a soma de 46% do primeiro valor com com 31% do
//segundo valor com 14% do terceiro valor
var
V1,V2,V3,Soma:real

inicio

escreva("digite o primeiro valor:")
leia(V1)
escreva("digite o segundo valor:")
leia(V2)
escreva("digite o terceiro valor:")
leia(V3)
Soma<- ((V1*0.46)+(V2*0.31)+(V3*0.14))
Escreva("O valor da soma é:",Soma)


fimalgoritmo
