algoritmo "semnome"
//29) Solicite dois valores e apresente o resto da divisão da soma dos mesmos por 3

var
V1,V2,V3,Soma:inteiro
Resto:real
inicio

escreva("digite o primeiro numero:")
leia(V1)
escreva("digite o segundo numero:")
leia(V2)
escreva("digite o terceiro numero:")
leia(V3)
Soma<- (V1 + V2 + V3)
Resto<- (Soma%3)
escreva("O valor da soma dos tres numeros, e divido por tres sobra:",Resto)




fimalgoritmo
