algoritmo "Aumento de Salário"
//2) Ler duas variáveis numérica, e apresentar a soma das mesmas,
// acumulando ou não em outra variável.
var
Varia1: real
Varia2:  real
Varia3: real
inicio
  Escreva("Digite o numero da primeira variavel ")
  Leia(Varia1)
  Escreva("Digite o numero da segunda variavel")
  Leia(Varia2)

  Varia3 <- Varia1 + Varia2

  Escreva("A soma das duas variaveis é: ", Varia3)
fimalgoritmo
