algoritmo "semnome"
//30) Solicite o nome, a idade, a cidade e o salario. Apresente em seguida todos os dados com o salário reajustado em
//9,45%

var
Nome,Cidade:caracter
Salario,Reajuste:real
inicio

escreva("digite o nome:")
leia(Nome)
escreva("digite a cidade:")
leia(Cidade)
escreva("digite o salario:")
leia(Salario)
Reajuste<- (Salario *1.0945)
escreval("O Nome é:",Nome)
escreval("A cidade é:",Cidade)
escreval("O Reajuste do salario é:",Reajuste)





fimalgoritmo
