algoritmo "semnome"
//4) Solicite dois valores e apresente o maior e o menor elemento. Caso sejam iguais, informe ao usuário
var
V1,V2:real
inicio
escreva("digite um numero:")
leia(V1)
escreva("digite um numero:")
leia(V2)
se (V1-V2)>=1 entao
   escreva("O primeiro numero é o maior valor")
fimse
se (V2-V1)>=1 entao
   escreva("O segundo numero é o maior valor")
fimse
se (V1-V2)=0 entao
escreva("O dois numeros informados são iguais")
fimse


fimalgoritmo
